import type { ProspectConfig } from './_types';

export const qualifyConfig: ProspectConfig = {
  slug: 'qualify',
  prospect_name: 'Generic qualification',
  top_meta: 'Diagnostic intake · pre-call',
  welcome: {
    headline: 'Before we talk.',
    body: "A few questions so I can read the room before we get in it. Plain English is perfect. The goal is to skip the discovery dance and spend the call on what matters.\n\nAbout 10 minutes. Your answers come straight to my inbox.\n\n- Fred",
    cta_label: 'Start',
  },
  thank_you: {
    headline: 'Got it.',
    body: "I'll read every word before our call.\n\n- Fred",
  },
  email_to: 'NOTIFICATION_EMAIL',
  questions: [
    {
      id: 'company_url',
      type: 'url',
      text: 'Company URL',
      emphasis: ['URL'],
      helper: "Just paste it. http or https, doesn't matter.",
      placeholder: 'https://',
      validate: 'url',
    },
    {
      id: 'name_role',
      type: 'two_field',
      text: 'Your name and role',
      emphasis: ['name and role'],
      fields: [
        { id: 'name', label: 'Full name', placeholder: 'Jane Smith' },
        { id: 'role', label: 'Role', placeholder: 'Founder / Head of growth / etc.' },
      ],
    },
    {
      id: 'stakeholders',
      type: 'long_text',
      text: 'Who else needs to be in the room for this to move forward?',
      emphasis: ['for this to move forward'],
      helper: "Be specific. 'Just me' is a valid answer.",
      placeholder: 'Names, roles, or just me.',
    },
    {
      id: 'broken',
      type: 'long_text',
      text: "What's broken right now?",
      emphasis: ['right now'],
      helper: "Plain English. Don't sell it, describe it.",
      placeholder: 'The honest version.',
    },
    {
      id: 'tried',
      type: 'long_text',
      text: 'What have you already tried to fix it?',
      emphasis: ['already tried'],
      helper: 'Agencies, tools, internal hires, whatever.',
      placeholder: 'List the failed attempts.',
    },
    {
      id: 'budget',
      type: 'single_select_letter',
      text: 'Rough budget range to solve this',
      emphasis: ['to solve this'],
      helper: 'Press a letter, or click. No need to be exact.',
      options: [
        { key: 'A', label: 'Under $5k' },
        { key: 'B', label: '$5k to $15k' },
        { key: 'C', label: '$15k to $50k' },
        { key: 'D', label: '$50k+' },
        { key: 'E', label: 'Not sure yet' },
      ],
    },
    {
      id: 'win',
      type: 'long_text',
      text: 'What does a clear win look like 90 days from now?',
      emphasis: ['90 days from now'],
      helper: 'Specific outcomes, not vibes.',
      placeholder: "Numbers if you have them. Behaviours if you don't.",
    },
    {
      id: 'stack',
      type: 'five_field',
      text: 'Current stack',
      emphasis: ['stack'],
      helper: 'All optional. N/A is allowed everywhere.',
      optional: true,
      fields: [
        { id: 'crm', label: 'CRM', optional: true },
        { id: 'marketing_automation', label: 'Marketing automation', optional: true },
        { id: 'ad_platforms', label: 'Ad platforms', optional: true },
        { id: 'analytics', label: 'Analytics', optional: true },
        { id: 'data_warehouse', label: 'Data warehouse', optional: true },
      ],
    },
    {
      id: 'other_context',
      type: 'long_text',
      text: 'Anything else I should know before we talk?',
      emphasis: ['before we talk'],
      placeholder: 'Optional.',
      optional: true,
    },
  ],
};
